### ISSUE TITLE
My own Branch

### ISSUE THREAD

**Issue by NotThatICare** [SmurfyBlue/UD-F95-Community-Version#4]
I'd like my own branch so that way I don't have to make any commits to the other two and so I have a branch that I don't need anyone's approval for. I'm testing out an alternative to your phone back button that seems to work but that might have some potential consequences. Really we all should have our own branch as I think that's pretty standard for most projects.

**Comment by SmurfyBlue** [comment]
That would also mean that everytime WE update you don't get updated files tho...
I'm not sure this is a smart idea :/
And yes that is standard for most projects now-a-days however most projects don't work with RPGMaker VX Ace's ridiculous file system.
We have to be very careful when merging branches because it'll just overwrite all the files, this means that if we don't have at least ONE branch with ONLY the newest of the newest edits, we'll lose half the work we've done on every merge!

I'll "assign" this issue to everyone so that they can also have a say in it.

Also, if you test your phone back button code carefully, think it all works, send it over so someone else can test it and give their opinions.
If it works it's in, if it doesn't you'll get feedback.
